"""TSC-005: scenario group → markdown projection.

Covers the three things that make the projection trustworthy: it is
idempotent, a hand edit is refused rather than overwritten, and a group whose
scenarios were all retired keeps its document.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING

import pytest

from cod_doc.domain.entities import (
    ScenarioKind,
    ScenarioLinkKind,
    ScenarioRelation,
)
from cod_doc.infra.db import make_session_factory, transactional
from cod_doc.infra.models import ProjectModel
from cod_doc.services import projection_service, scenario_service
from cod_doc.services.projection_service import ExportGuardError

if TYPE_CHECKING:
    from pathlib import Path

GROUP = "plan-management"


def _seed(session, root: Path) -> int:  # type: ignore[no-untyped-def]
    now = datetime.now(UTC)
    proj = ProjectModel(slug="scn", title="P", root_path=str(root), config_json={})
    proj.created = now
    proj.updated = now
    session.add(proj)
    session.flush()
    return proj.row_id


def _create(session, pid: int, **kw):  # type: ignore[no-untyped-def]
    params = {
        "title": "Plan progress recomputes after a task completes",
        "kind": ScenarioKind.HAPPY_PATH,
        "group_key": GROUP,
        "preconditions": "A plan with one open task exists.",
        "expected": "plan_progress reports one task done.",
        "steps": ["Complete the task", "Read the plan progress"],
        "author": "human:test",
    }
    params.update(kw)
    return scenario_service.create(session, project_id=pid, **params)


def _export(session, pid: int, root: Path):  # type: ignore[no-untyped-def]
    return scenario_service.export_group(
        session,
        project_id=pid,
        group_key=GROUP,
        root_path=root,
        author="human:test",
        own_checkout_only=False,
    )


def _target(root: Path) -> Path:
    return root / "docs" / "system" / "scenarios" / f"{GROUP}.md"


# --------------------------------------------------------------------------- #
# first export                                                                 #
# --------------------------------------------------------------------------- #


def test_export_writes_file_with_scenario_sections(engine_with_schema, tmp_path) -> None:  # type: ignore[no-untyped-def]
    factory = make_session_factory(engine_with_schema)
    with transactional(factory) as session:
        pid = _seed(session, tmp_path)
        _create(session, pid)
        result = _export(session, pid, tmp_path)

    assert result.written is True
    body = _target(tmp_path).read_text()
    assert "## Overview" in body
    assert "## SCN-001 — Plan progress recomputes after a task completes" in body
    assert "### Preconditions" in body
    assert "1. Complete the task" in body
    assert "generated by scenario_service" in body


def test_export_records_kind_counts(engine_with_schema, tmp_path) -> None:  # type: ignore[no-untyped-def]
    factory = make_session_factory(engine_with_schema)
    with transactional(factory) as session:
        pid = _seed(session, tmp_path)
        _create(session, pid, kind=ScenarioKind.HAPPY_PATH)
        _create(session, pid, kind=ScenarioKind.ERROR_PATH)
        _export(session, pid, tmp_path)

    body = _target(tmp_path).read_text()
    assert "| `happy_path` | 1 |" in body
    assert "| `error_path` | 1 |" in body
    assert "| **total** | **2** |" in body


def test_links_are_rendered(engine_with_schema, tmp_path) -> None:  # type: ignore[no-untyped-def]
    factory = make_session_factory(engine_with_schema)
    with transactional(factory) as session:
        pid = _seed(session, tmp_path)
        s = _create(session, pid)
        scenario_service.link(
            session,
            project_id=pid,
            scenario_id=s.scenario_id,
            to_kind=ScenarioLinkKind.CRITERION,
            to_ref="US-013#2",
            relation=ScenarioRelation.VERIFIES,
            author="human:test",
        )
        _export(session, pid, tmp_path)

    assert "`verifies` → `criterion:US-013#2`" in _target(tmp_path).read_text()


# --------------------------------------------------------------------------- #
# idempotency                                                                  #
# --------------------------------------------------------------------------- #


def test_second_export_writes_nothing(engine_with_schema, tmp_path) -> None:  # type: ignore[no-untyped-def]
    factory = make_session_factory(engine_with_schema)
    with transactional(factory) as session:
        pid = _seed(session, tmp_path)
        _create(session, pid)
        _export(session, pid, tmp_path)
        second = _export(session, pid, tmp_path)

    assert second.written is False


def test_reexport_after_edit_updates_file(engine_with_schema, tmp_path) -> None:  # type: ignore[no-untyped-def]
    factory = make_session_factory(engine_with_schema)
    with transactional(factory) as session:
        pid = _seed(session, tmp_path)
        s = _create(session, pid)
        _export(session, pid, tmp_path)
        scenario_service.update(
            session,
            project_id=pid,
            scenario_id=s.scenario_id,
            author="human:test",
            title="Renamed scenario",
        )
        result = _export(session, pid, tmp_path)

    assert result.written is True
    assert "SCN-001 — Renamed scenario" in _target(tmp_path).read_text()


# --------------------------------------------------------------------------- #
# guards                                                                       #
# --------------------------------------------------------------------------- #


def test_hand_edited_file_is_refused(engine_with_schema, tmp_path) -> None:  # type: ignore[no-untyped-def]
    """A hand edit of a generated file is drift, not input."""
    factory = make_session_factory(engine_with_schema)
    with transactional(factory) as session:
        pid = _seed(session, tmp_path)
        s = _create(session, pid)
        _export(session, pid, tmp_path)

        target = _target(tmp_path)
        target.write_text(target.read_text() + "\nhand-written line\n")

        scenario_service.update(
            session,
            project_id=pid,
            scenario_id=s.scenario_id,
            author="human:test",
            title="Renamed after a hand edit",
        )
        with pytest.raises(ExportGuardError):
            _export(session, pid, tmp_path)


def test_hand_edit_shows_up_as_drift(engine_with_schema, tmp_path) -> None:  # type: ignore[no-untyped-def]
    factory = make_session_factory(engine_with_schema)
    with transactional(factory) as session:
        pid = _seed(session, tmp_path)
        _create(session, pid)
        result = _export(session, pid, tmp_path)

        target = _target(tmp_path)
        target.write_text(target.read_text() + "\nhand-written line\n")

        report = projection_service.detect_drift(session, result.document_id, root_path=tmp_path)
    assert report.status.value == "edited_in_place"


# --------------------------------------------------------------------------- #
# retired scenarios                                                            #
# --------------------------------------------------------------------------- #


def test_retired_scenario_section_is_removed(engine_with_schema, tmp_path) -> None:  # type: ignore[no-untyped-def]
    factory = make_session_factory(engine_with_schema)
    with transactional(factory) as session:
        pid = _seed(session, tmp_path)
        first = _create(session, pid)
        _create(session, pid, kind=ScenarioKind.ERROR_PATH, title="Second")
        _export(session, pid, tmp_path)

        scenario_service.retire(
            session, project_id=pid, scenario_id=first.scenario_id, author="human:test"
        )
        _export(session, pid, tmp_path)

    body = _target(tmp_path).read_text()
    assert "## SCN-001" not in body
    assert "## SCN-002 — Second" in body


def test_group_with_everything_retired_keeps_document(engine_with_schema, tmp_path) -> None:  # type: ignore[no-untyped-def]
    """Deleting the document would break links and registries — keep the Overview."""
    factory = make_session_factory(engine_with_schema)
    with transactional(factory) as session:
        pid = _seed(session, tmp_path)
        s = _create(session, pid)
        _export(session, pid, tmp_path)
        scenario_service.retire(
            session, project_id=pid, scenario_id=s.scenario_id, author="human:test"
        )
        _export(session, pid, tmp_path)

    body = _target(tmp_path).read_text()
    assert "## Overview" in body
    assert "| **total** | **0** |" in body
    assert "## SCN-001" not in body


# --------------------------------------------------------------------------- #
# export_all + activity                                                        #
# --------------------------------------------------------------------------- #


def test_export_all_covers_every_group(engine_with_schema, tmp_path) -> None:  # type: ignore[no-untyped-def]
    factory = make_session_factory(engine_with_schema)
    with transactional(factory) as session:
        pid = _seed(session, tmp_path)
        _create(session, pid)
        _create(session, pid, group_key="doc-evolution", title="Drift is detected")
        results = scenario_service.export_all(
            session,
            project_id=pid,
            root_path=tmp_path,
            author="human:test",
            own_checkout_only=False,
        )

    assert len(results) == 2
    assert (tmp_path / "docs/system/scenarios/doc-evolution.md").exists()
    assert _target(tmp_path).exists()


def test_export_emits_activity_event(engine_with_schema, tmp_path) -> None:  # type: ignore[no-untyped-def]
    from sqlalchemy import select

    from cod_doc.infra.models import ActivityEventModel

    factory = make_session_factory(engine_with_schema)
    with transactional(factory) as session:
        pid = _seed(session, tmp_path)
        _create(session, pid)
        _export(session, pid, tmp_path)
        session.flush()
        kinds = [
            e.kind
            for e in session.execute(
                select(ActivityEventModel).where(ActivityEventModel.scope_kind == "scenario_group")
            ).scalars()
        ]
    assert kinds == ["scenario.exported"]
