"""Deterministic markdown rendering of one scenario group.

Pure: no session writes, no file I/O. `export.py` turns the sections this
module produces into `Section` rows and then into a file, so the same shape
survives the DB → markdown → DB round trip.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from cod_doc.domain.entities import ScenarioKind, ScenarioStatus

if TYPE_CHECKING:
    from cod_doc.domain.entities import Scenario, ScenarioLink, ScenarioStep

GENERATED_MARKER = (
    "<!-- generated by scenario_service — edit via `cod-doc scenario`, not this file -->"
)
OVERVIEW_ANCHOR = "overview"


@dataclass(slots=True)
class RenderedSection:
    anchor: str
    heading: str
    level: int
    body: str


def _overview_body(group_key: str, scenarios: list[Scenario]) -> str:
    live = [s for s in scenarios if s.status is not ScenarioStatus.RETIRED]
    counts: dict[str, int] = {}
    for scenario in live:
        counts[scenario.kind.value] = counts.get(scenario.kind.value, 0) + 1

    lines = [
        GENERATED_MARKER,
        "",
        f"Test scenarios for the **{group_key}** capability — the authoring half of",
        "[RFC 24 §9]. Coverage verdicts are not recorded here: whether a test proves a",
        "scenario is producer-derived evidence, kept separately.",
        "",
        f"Capability document: `docs/system/capabilities/{group_key}.md`",
        "",
        "| Kind | Count |",
        "|---|---|",
    ]
    lines.extend(f"| `{kind.value}` | {counts.get(kind.value, 0)} |" for kind in ScenarioKind)
    lines.append(f"| **total** | **{len(live)}** |")
    return "\n".join(lines)


def _scenario_body(
    scenario: Scenario,
    steps: list[ScenarioStep],
    links: list[ScenarioLink],
) -> str:
    lines = [
        f"**Kind:** `{scenario.kind.value}`",
        f"**Status:** `{scenario.status.value}`",
    ]
    if scenario.doc_key:
        anchor = f"#{scenario.section_anchor}" if scenario.section_anchor else ""
        lines.append(f"**Anchor:** `{scenario.doc_key}{anchor}`")
    lines.extend(["", "### Preconditions", "", scenario.preconditions.strip(), "", "### Steps", ""])
    if steps:
        lines.extend(f"{i}. {step.text.strip()}" for i, step in enumerate(steps, start=1))
    else:
        lines.append("_No steps recorded._")
    lines.extend(["", "### Expected result", "", scenario.expected.strip()])
    if scenario.notes and scenario.notes.strip():
        lines.extend(["", "### Notes", "", scenario.notes.strip()])
    if links:
        lines.extend(["", "### Links", ""])
        lines.extend(
            f"- `{link.relation.value}` → `{link.to_kind.value}:{link.to_ref}`" for link in links
        )
    return "\n".join(lines)


def render_sections(
    group_key: str,
    scenarios: list[Scenario],
    steps_by_scenario: dict[int, list[ScenarioStep]],
    links_by_scenario: dict[int, list[ScenarioLink]],
) -> list[RenderedSection]:
    """Overview section first, then one section per live scenario, in stable order."""
    sections = [
        RenderedSection(
            anchor=OVERVIEW_ANCHOR,
            heading="Overview",
            level=2,
            body=_overview_body(group_key, scenarios),
        )
    ]
    for scenario in scenarios:
        if scenario.status is ScenarioStatus.RETIRED:
            continue
        assert scenario.row_id is not None
        sections.append(
            RenderedSection(
                anchor=scenario.scenario_id.lower(),
                heading=f"{scenario.scenario_id} — {scenario.title}",
                level=2,
                body=_scenario_body(
                    scenario,
                    steps_by_scenario.get(scenario.row_id, []),
                    links_by_scenario.get(scenario.row_id, []),
                ),
            )
        )
    return sections


def render_group_markdown(
    group_key: str,
    scenarios: list[Scenario],
    steps_by_scenario: dict[int, list[ScenarioStep]],
    links_by_scenario: dict[int, list[ScenarioLink]],
) -> str:
    """Render the whole group as one markdown body (headings included)."""
    sections = render_sections(group_key, scenarios, steps_by_scenario, links_by_scenario)
    chunks = [f"{'#' * s.level} {s.heading}\n\n{s.body}" for s in sections]
    return "\n\n".join(chunks) + "\n"
